apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ship
  labels:
    access-ship-db: "1"
spec:
  template:
    metadata:
      labels:
        access-ship-db: "1"
    spec:
      containers:
        - image: eu.gcr.io/mhaddon/ship:v11
          env:
           - name: MONGO_USERNAME
             valueFrom:
               secretKeyRef:
                 name: ship-db-credentials
                 key: username
           - name: MONGO_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: ship-db-credentials
                 key: password
           - name: MONGO_COLLECTION
             valueFrom:
               secretKeyRef:
                 name: ship-db-credentials
                 key: collection
           - name: MONGO_DB
             valueFrom:
               secretKeyRef:
                 name: ship-db-credentials
                 key: database
           - name: MONGO_DOMAIN
             value: 'ship-db.default.svc.cluster.local'
           - name: MONGO_PORT
             value: '27017'
          resources:
            limits:
              cpu: "100m"
              memory: 256Mi
            requests:
              cpu: "50m"
              memory: 64Mi

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ship-entry-route
spec:
  gateways:
    - knative-serving/cluster-local-gateway
    - knative-serving/knative-ingress-gateway
  hosts:
    - ship.tiw.io
  http:
    - rewrite:
        authority: ship.default.tiw.io
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
          weight: 100
