apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  tiw.io: ""

---

apiVersion: pubsub.cloud.google.com/v1alpha1
kind: PullSubscription
metadata:
  name: ingress-source
spec:
  topic: ingress
  #  mode: PushCompatible
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default

---

apiVersion: pubsub.cloud.google.com/v1alpha1
kind: PullSubscription
metadata:
  name: normalised-source
spec:
  topic: normalised
  #  mode: PushCompatible
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default

---

apiVersion: pubsub.cloud.google.com/v1alpha1
kind: Topic
metadata:
  name: ingress-topic
spec:
  topic: ingress
  propagationPolicy: CreateDelete

---

apiVersion: pubsub.cloud.google.com/v1alpha1
kind: Topic
metadata:
  name: normalised-topic
spec:
  topic: normalised
  propagationPolicy: CreateDelete
