# https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform

#apiVersion: iam.cnrm.cloud.google.com/v1alpha1
#kind: IAMServiceAccount
#metadata:
#  name: pubsub-app
#spec:
#  displayName: Service account for PubSub example
#
#---
#
#apiVersion: iam.cnrm.cloud.google.com/v1alpha1
#kind: IAMPolicyMember
#metadata:
#  name: policy-member-binding
#spec:
#  member: serviceAccount:pubsub-app@mhaddon.iam.gserviceaccount.com
#  role: roles/pubsub.subscriber
#  resourceRef:
#    kind: Project
#    name: mhaddon
#
#---
#
#apiVersion: iam.cnrm.cloud.google.com/v1alpha1
#kind: IAMServiceAccountKey
#metadata:
#  name: pubsub-key
#spec:
#  publicKeyType: TYPE_X509_PEM_FILE
#  keyAlgorithm: KEY_ALG_RSA_2048
#  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
#  serviceAccountRef:
#    name: pubsub-app
