apiVersion: v1
kind: ServiceAccount
metadata:
  name: ship-request-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-request-frontend
  namespace: ship-app-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ship-request-frontend
  template:
    metadata:
      labels:
        component: ship-request-frontend
    spec:
      serviceAccountName: ship-request-frontend
      containers:
        - name: ship-request-frontend
          image: eu.gcr.io/mhaddon/ship-request-frontend:v5
          resources:
            limits:
              cpu: "100m"
              memory: 256Mi
            requests:
              cpu: "50m"
              memory: 64Mi
          ports:
            - containerPort: 80

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ship-request-frontend
  namespace: ship-app-kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ship-request-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 1k

---

apiVersion: v1
kind: Service
metadata:
  name: ship-request-frontend
  namespace: ship-app-kafka
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: ship-request-frontend
  type: ClusterIP

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ship-request-frontend
  namespace: ship-app-kafka
spec:
  hosts:
    - "tiw.io"
  gateways:
    - tiwio-gateway
  http:
    - route:
        - destination:
            host: ship-request-frontend
            port:
              number: 80
